name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Unit tests
        run: bash ./gradlew test --stacktrace